### ISSUE TITLE
万灵当歌资料片专题

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/topic#17]
最晚10月第2周要开始做

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/5c321522-39e4-45c7-ab83-dded2b446015)
- [x] 已完成

**Comment by zixuan1986** [comment]
所有的标题和模块都第一次打开的时候加载一次动画，动画完了之后就不会再动，具体参考横刀断浪
https://www.jx3box.com/topic/hengdaoduanlang/#/
![image](https://github.com/JX3BOX/topic/assets/40552272/7a6995a1-0b24-440b-872f-1519b930da6f)
![image](https://github.com/JX3BOX/topic/assets/40552272/2a920167-a56c-4286-8254-d742480231f5)
![image](https://github.com/JX3BOX/topic/assets/40552272/02793b56-872a-40b4-89aa-6a851b38fa08)

- [x] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/2a920167-a56c-4286-8254-d742480231f5)
- [ ] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/97cb7b74-1f2b-49bc-beaf-7d0b1ba6c483)
![image](https://github.com/JX3BOX/topic/assets/40552272/84ec97d4-13a2-4b04-bd7b-a6cae974d73f)
![image](https://github.com/JX3BOX/topic/assets/40552272/117cc9e2-d9e6-4c07-a42d-2833602f4032)

- [x] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/3c131575-ac9c-4f6d-bc20-2b861d99512b)
背景图是有个阴影效果的，需要加上遮罩，这个横条是遮罩并不是图片上面的
![image](https://github.com/JX3BOX/topic/assets/40552272/79e90ae2-2052-4e72-9f8d-511a1bb9c780)

![image](https://github.com/JX3BOX/topic/assets/40552272/da8252c4-5da2-4fa9-80a9-15721d1b15eb)

- [x] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/794852d1-0867-49d1-a3f4-bae6b23cd830)
![image](https://github.com/JX3BOX/topic/assets/40552272/ec4a69cb-aa81-4c19-9b53-5b44c37f00ab)

- [x] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/84ec97d4-13a2-4b04-bd7b-a6cae974d73f)
- [x] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/1240229d-cdcd-4120-9f99-7865fd51836c)
![image](https://github.com/JX3BOX/topic/assets/40552272/3af0abc2-2245-4d37-a38b-145a774571e1)

- [x] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/a647128b-ecda-4937-89b6-565916a40d08)
- [x] 已完成

**Comment by zixuan1986** [comment]
![image](https://github.com/JX3BOX/topic/assets/40552272/0e829bc3-de03-4196-857f-7ae6c89fa310)
手机端的适配稍微调一下
- [x] 已完成

**Comment by iRuxu** [comment]
## 链接
![c8568a65349890262782083e85917666](https://github.com/JX3BOX/topic/assets/8476969/1b23177a-c87c-41c8-9191-bbd1f8008525)
新窗打开

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="555" alt="image" src="https://github.com/JX3BOX/topic/assets/8476969/3a4a5c70-0f95-41e8-82c9-164deb1fe8a8">

链接是到/face，新窗

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="305" alt="image" src="https://github.com/JX3BOX/topic/assets/8476969/0e69bb4c-de42-47a9-a06e-eac23994aedb">

链接地址分别是
/fb/?fb_name=xxx
注意新窗

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="489" alt="image" src="https://github.com/JX3BOX/topic/assets/8476969/068662a9-0ec6-47d6-bbbc-6a258c90bfed">

缺失两个图，找设计要

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="480" alt="image" src="https://github.com/JX3BOX/topic/assets/8476969/bd8e4466-67f4-4ac7-ac9c-e075e4309399">

链接分别是
/macro/?subtype=山海心诀
/bps/?subtype=山海心诀

- [x] 已完成
