### ISSUE TITLE
圣殿风云资料片专题

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/topic#4]
- [x] 专题导航页
- [x] 专题主页
- [x] 专题内页
- [x] 资讯页

**Comment by iRuxu** [comment]
## 一期验收问题
![image](https://user-images.githubusercontent.com/8476969/160238385-7b9f29bc-82c2-4644-b66e-cb712a37578d.png)
没有居中

- [x] 已完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/160238510-ff1c96b9-c1b6-4351-b222-954185db00d8.png)

地址用 https://origin.jx3box.com/notice/38368

另外还加上上赛季的征稿图  然后地址用 https://origin.jx3box.com/notice/38367

- [x] 已完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/160238579-9202d45a-a158-4140-8462-f5469b576e43.png)

对应的两个图要换

![image](https://user-images.githubusercontent.com/8476969/160238588-8f456254-dc10-4a53-8c71-97bd95f9ab93.png)

按钮的地址也要换

第一个用 https://origin.jx3box.com/fb/#/?fb_zlp=%E9%A3%8E%E8%B5%B7%E7%A8%BB%E9%A6%99&fb_name=%E8%8D%BB%E8%8A%B1%E5%AE%AB%E5%89%8D%E5%B1%B1

第二个用  https://origin.jx3box.com/fb/#/?fb_zlp=%E5%B7%B4%E8%9C%80%E9%A3%8E%E4%BA%91&fb_name=%E8%8D%BB%E8%8A%B1%E5%9C%A3%E6%AE%BF

- [x] 已完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/160238712-eaae8d37-686e-4e65-9f1e-6ea0fdc53ed4.png)


内页第一屏切换后的内容不正确

- [x] 已完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/160238695-26e24e52-b3c5-446b-a4c1-3ffca5b1104a.png)

底部的kuandu宽度也需要和外层保持一样

- [x] 已完成

**Comment by zixuan1986** [comment]
已完成
